// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace StockManageBusinessObjects.Models;

public partial class Account
{
    [Key]
    [StringLength(50)]
    public string Email { get; set; }

    [StringLength(100)]
    public string UserName { get; set; }

    [StringLength(50)]
    public string Password { get; set; }

    [StringLength(50)]
    public string FullName { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Birthday { get; set; }

    [StringLength(10)]
    public string Status { get; set; }

    public int? RoleID { get; set; }

    public string? RefreshToken { get; set; }
}