// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace StockManageBusinessObjects.Models;

public partial class Stock
{
    [StringLength(50)]
    public string StockID { get; set; }

    [Key]
    [StringLength(10)]
    public string StockCode { get; set; }

    [StringLength(50)]
    public string StockName { get; set; }

    [StringLength(50)]
    public string CompanyName { get; set; }

    [StringLength(50)]
    public string Email { get; set; }

    [StringLength(50)]
    public string Exchange { get; set; }

    [StringLength(50)]
    public string Address { get; set; }

    public int? CurrentPrice { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    [InverseProperty("StockCodeNavigation")]
    public virtual ICollection<StocksHistory> StocksHistories { get; set; } = new List<StocksHistory>();
}