// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace StockManageBusinessObjects.Models;

[Table("StocksHistory")]
public partial class StocksHistory
{
    [Key]
    public int ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ExchangeDate { get; set; }

    public int? Price { get; set; }

    public int? OpenPrice { get; set; }

    public int? ClosePrice { get; set; }

    public int? MaxPrice { get; set; }

    public int? MinPrice { get; set; }

    public int? Volume { get; set; }

    [StringLength(10)]
    public string StockCode { get; set; }

    [ForeignKey("StockCode")]
    [InverseProperty("StocksHistories")]
    public virtual Stock StockCodeNavigation { get; set; }
}